package com.dinnerOrdering.ui.forms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.CheckBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminFormDesign extends VerticalLayout {
    protected Grid<com.dinnerOrdering.entities.OrderEntity> grid;
    protected Button deleteSelectedRowsBtn;
    protected TextField countToCopyText;
    protected Button copyRowBtn;
    protected ComboBox<String> nameComb;
    protected Label balanceLabel;
    protected TextField insertSumText;
    protected Button insertButton;
    protected DateField dateField;
    protected Label sumForDayLabel;
    protected Button getTableButton;
    protected Grid<com.dinnerOrdering.entities.EmailEntity> emailGrid;
    protected Button delEmailBtn;
    protected TextField addEmailTxt;
    protected Button addEmailBtn;
    protected CheckBox enableAutoSendingChb;
    protected Button makeAutoOrdersAndSendMailButton;

    public AdminFormDesign() {
        Design.read(this);
    }
}
