package com.dinnerOrdering.ui.forms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserFormDesign extends GridLayout {
    protected Label headerLabel;
    protected ComboBox<String> setComb;
    protected Button showSoupsBtn;
    protected ComboBox<String> saladComb;
    protected ComboBox<String> hotComb;
    protected ComboBox<String> hosperComb;
    protected ComboBox<String> fixingsComb;
    protected ComboBox<String> drinkComb;
    protected ComboBox<String> breadComb;
    protected Label priceLabel;
    protected Label balanceLabel;
    protected Button confirmButton;
    protected Label messageLabel;
    protected VerticalLayout currOrdLayout;
    protected Label currOrderLbl;
    protected Label setLbl;
    protected Label soupLbl;
    protected Label saladLbl;
    protected Label hotLbl;
    protected Label hospLbl;
    protected Label fixingsLbl;
    protected Label drinkLbl;
    protected Label breadLbl;
    protected Button delCurrButton;
    protected CheckBox autoupdateChb;

    public UserFormDesign() {
        Design.read(this);
    }
}
